name: Prompt Evaluation

on:
  pull_request:
    branches:
      - main

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install typing_extensions google-genai

      # Decode evaluation script from base64 secret
      - name: Decode and write prompt evaluation script
        run: |
          echo "${{ secrets.PROMPT_SCRIPT_B64 }}" | base64 -d > prompt_eval.py

      # Run the prompt evaluation script
      - name: Run prompt evaluation script
        env:
            PROMPT_EVAL_API_KEY: ${{ secrets.PROMPT_EVAL_API_KEY }}
        run: |
          if [[ -f submission/prompt.txt ]]; then
            python prompt_eval.py 
          else
            echo "submission/prompt.txt file is missing. Skipping evaluation."
            exit 0 
          fi

      # Cleanup
      - name: Delete sensitive files
        run: |
          rm -f prompt_eval.py